-- -- Categories
-- CREATE TABLE IF NOT EXISTS categories (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   name VARCHAR(255) UNIQUE NOT NULL,
--   slug VARCHAR(255) UNIQUE,
--   description TEXT,
--   image_url TEXT,
--   is_active BOOLEAN DEFAULT true,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Products
-- CREATE TABLE IF NOT EXISTS products (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   name VARCHAR(255) NOT NULL,
--   slug VARCHAR(255) UNIQUE,
--   description TEXT,
--   price DECIMAL(10, 2) NOT NULL CHECK (price >= 0),
--   category_id UUID REFERENCES categories(id) ON DELETE SET NULL, -- Changed: Removed NOT NULL
--   is_active BOOLEAN DEFAULT true,
--   is_featured BOOLEAN DEFAULT false,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Product images
-- CREATE TABLE IF NOT EXISTS product_images (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
--   image_url TEXT NOT NULL,
--   alt_text VARCHAR(255),
--   is_primary BOOLEAN DEFAULT false,
--   display_order INTEGER DEFAULT 0,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Orders (Cash on Delivery only)
-- CREATE TABLE IF NOT EXISTS orders (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   order_number VARCHAR(50) UNIQUE NOT NULL,
--   status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled')), -- Added CHECK constraint
--   subtotal DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
--   tax DECIMAL(12, 2) DEFAULT 0 CHECK (tax >= 0),
--   shipping_cost DECIMAL(12, 2) DEFAULT 0 CHECK (shipping_cost >= 0),
--   total DECIMAL(12, 2) NOT NULL CHECK (total >= 0),
--   customer_name VARCHAR(255) NOT NULL,
--   customer_email VARCHAR(255),
--   customer_phone VARCHAR(20) NOT NULL,
--   shipping_address TEXT NOT NULL,
--   notes TEXT,
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Order items
-- CREATE TABLE IF NOT EXISTS order_items (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
--   product_id UUID REFERENCES products(id) ON DELETE SET NULL,
--   product_name VARCHAR(255) NOT NULL, -- Added: Store product name for historical records
--   quantity INTEGER NOT NULL CHECK (quantity > 0),
--   unit_price DECIMAL(10, 2) NOT NULL CHECK (unit_price >= 0),
--   subtotal DECIMAL(12, 2) NOT NULL CHECK (subtotal >= 0),
--   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );

-- -- Create indexes for better query performance
-- CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
-- CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
-- CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
-- CREATE INDEX IF NOT EXISTS idx_products_featured ON products(is_featured) WHERE is_featured = true; -- Added
-- CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
-- CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
-- CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
-- CREATE INDEX IF NOT EXISTS idx_orders_number ON orders(order_number);
-- CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
-- CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON order_items(product_id); -- Added

-- -- Ensure only ONE primary image per product
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_product_images_one_primary 
-- ON product_images (product_id) 
-- WHERE is_primary = true;

-- -- Function to auto-update updated_at timestamp
-- CREATE OR REPLACE FUNCTION update_updated_at_column()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   NEW.updated_at = CURRENT_TIMESTAMP;
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- -- Triggers for updated_at
-- CREATE TRIGGER trigger_categories_updated_at
-- BEFORE UPDATE ON categories
-- FOR EACH ROW
-- EXECUTE FUNCTION update_updated_at_column();

-- CREATE TRIGGER trigger_products_updated_at
-- BEFORE UPDATE ON products
-- FOR EACH ROW
-- EXECUTE FUNCTION update_updated_at_column();

-- CREATE TRIGGER trigger_orders_updated_at
-- BEFORE UPDATE ON orders
-- FOR EACH ROW
-- EXECUTE FUNCTION update_updated_at_column();

-- -- Trigger to ensure single primary image
-- CREATE OR REPLACE FUNCTION ensure_single_primary_image()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   IF NEW.is_primary = true THEN
--     UPDATE product_images 
--     SET is_primary = false 
--     WHERE product_id = NEW.product_id 
--       AND id != NEW.id 
--       AND is_primary = true;
--   END IF;
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- CREATE TRIGGER trigger_ensure_single_primary_image
-- BEFORE INSERT OR UPDATE OF is_primary ON product_images
-- FOR EACH ROW
-- EXECUTE FUNCTION ensure_single_primary_image();